"""Add authored neighborhood content; only replaces this wave's own IDs."""
import json
from pathlib import Path
P=Path("game/presets/core")
def loc(ru,en): return dict(ru=ru,en=en)
# id, names, position, biography, craft, city (three bilingual paragraphs each).
people=[
("ivo","Иво","Ivo",[-8,22],[
("Я Иво, флорист. Эти розы пережили два отключения света и один налёт. Теперь я поливаю их по расписанию, а не по настроению.","I'm Ivo, the florist. These roses survived two blackouts and a raid. Now I water them on a schedule, not whenever inspiration strikes."),
("Раньше я прятал кружевной фартук под рабочей курткой. Потом понял: чужое неодобрение не сделает мои руки умелее.","I used to hide my lace apron under a work jacket. Then I realized other people's disapproval would never make my hands more skilled."),
("Первый букет в новой лавке я подарил самому себе. Неловко? Немного. Зато впервые не ждал повода, который разрешит мне радоваться.","I gave the first bouquet in my new shop to myself. Awkward? A little. But I finally stopped waiting for permission to be happy.")],[
("У розы с неоновым краем лепестки холодные. Свечение не означает, что ей нужен ток: она накапливает свет днём.","A neon-edged rose has cool petals. Glowing doesn't mean it needs electricity; it stores light during the day."),
("Для Рена я собираю маленькие букеты без сильного запаха. Чай должен пахнуть чаем, а цветы — не спорить с ним.","Ren gets small arrangements without a strong scent. Tea should smell like tea; flowers shouldn't argue with it."),
("Хочешь подарить цветы парню — спроси, что ему нравится. Не существует универсального букета для всех нежных людей.","Buying flowers for a boy? Ask what he likes. There is no universal bouquet for every gentle person.")],[
("Ив выращивает зелень у южной дороги. Я продаю срезанные цветы, он даёт им остаться живыми. Мы спорим и прекрасно ладим.","Yves grows plants by the southern road. I sell cut flowers; he lets them stay alive. We disagree and get along beautifully."),
("Эмиль откладывает для меня бумагу от муки. Из неё выходят хорошие обёртки: город держится на таких мелочах.","Emil saves flour paper for me. It makes good wrapping. Little exchanges like that keep the city together."),
("Когда Мика приносит письмо без обратного адреса, я не гадаю, кто его написал. Чужая нежность не обязана быть городской новостью.","When Mika brings a letter with no return address, I don't guess who wrote it. Other people's affection doesn't have to become public news.")]),
("noel","Ноэль","Noel",[8,24],[
("Ноэль. Архивист. Если слышишь, что я разговариваю с книгой, не мешай: иногда это единственный способ поймать ошибку переписчика.","Noel. Archivist. If you hear me talking to a book, don't interrupt. Sometimes that's the only way to catch a copyist's mistake."),
("В старой описи мой жилет назвали женским. Я исправил запись на бархатный. Ткань описали неверно; всё остальное к учёту не относится.","An old inventory called my waistcoat women's clothing. I corrected it to velvet. The fabric was wrong; the rest is irrelevant to cataloguing."),
("Я сохраняю не только подвиги. Списки покупок расскажут потомкам о нас больше, чем ещё один памятник человеку с мечом.","I preserve more than heroic deeds. Shopping lists will tell our descendants more about us than another statue of a man with a sword.")],[
("Залитую страницу нельзя сушить над открытым огнём. Проложи листы чистой бумагой и позови меня. Терпение дешевле утраченной памяти.","Never dry a soaked page over an open flame. Separate the pages with clean paper and call me. Patience costs less than lost memory."),
("В заметках исследователей встречаются повторы. Это не обязательно ложь: двое могли увидеть одно и то же с разных сторон.","Researchers repeat one another sometimes. That isn't necessarily a lie; two people may have seen the same event from different angles."),
("У меня есть полка для незаконченных историй. Пустая последняя страница лучше выдуманного счастливого конца.","I keep a shelf for unfinished stories. A blank final page is better than an invented happy ending.")],[
("Люсьен думает, что я прихожу слушать его ради тишины между песнями. Я прихожу ради песен. Просто не умею красиво об этом сказать.","Lucien thinks I come for the silence between songs. I come for the songs. I'm simply bad at saying that elegantly."),
("У учёного спроси про эхо в катакомбах. Запись и воспоминание — разные вещи; не всякому голосу из стены стоит доверять.","Ask the scientist about catacomb echoes. A recording isn't a memory; not every voice in a wall deserves your trust."),
("Если найдёшь чьё-то имя, не стирай его ради более красивой надписи. Город уже слишком часто начинал историю заново.","If you find someone's name, don't erase it for a prettier inscription. This city has restarted its history too often.")]),
("lucien","Люсьен","Lucien",[-7,32],[
("Я Люсьен. Играю здесь по вечерам. Днём репетирую не потому, что вдохновение пришло, а потому, что вечером люди заслуживают хорошую музыку.","I'm Lucien. I play here in the evenings. I practice by day because people deserve good music, not because inspiration arrived."),
("Первое выступление в чулках я помню лучше первого концерта. Руки дрожали, смычок скрипел. Рен просто принёс воды и попросил следующую песню.","I remember my first performance in stockings better than my first concert. My hands shook. Ren brought water and asked for another song."),
("Теперь я выбираю одежду по тому, удобно ли держать скрипку. Иногда смелость выглядит как правильно подшитый рукав.","Now I choose clothes by how comfortably I can hold my violin. Sometimes courage looks like a properly hemmed sleeve.")],[
("Катакомбы возвращают звук с задержкой. Не подстраивай шаг под эхо: оно знает, где ты был, а не где безопасно.","Catacombs return sound with a delay. Don't match your steps to an echo; it knows where you were, not where it's safe."),
("Моя скрипка треснула во время эвакуации. Эш укрепил футляр, Сайлас сменил подкладку. Поэтому на сцене нас всегда немного больше одного.","My violin cracked during the evacuation. Ash reinforced its case and Silas replaced the lining. That's why I'm never truly alone on stage."),
("Я не играю громче сирены. Когда начинается тревога, музыка останавливается. Люди должны услышать дорогу домой.","I never try to outplay a siren. When an alarm starts, the music stops. People need to hear their way home.")],[
("Ноэль стоит с краю и делает вид, что читает. Каждый раз переворачивает страницу в одном и том же месте песни.","Noel stands at the edge and pretends to read. He turns a page at exactly the same point in every song."),
("Эмиль просит весёлую мелодию для очереди. Я написал короткую — чтобы никто не успел выучить её и возненавидеть.","Emil asked for a cheerful tune for his queue. I wrote a short one so nobody could learn it well enough to hate it."),
("Вечер квартала начнётся, когда будет безопасно. Афиши могут подождать; живые слушатели важнее красивого расписания.","The neighborhood evening will happen when it's safe. Posters can wait; living listeners matter more than a beautiful schedule.")]),
("ash","Эш","Ash",[7,34],[
("Эш. Ремонтирую свет и чужие поспешные решения. Если лампа шипит, отойди. Если шиплю я — принеси чай.","Ash. I repair lights and other people's hasty decisions. If a lamp hisses, step away. If I hiss, bring tea."),
("Розовую ленту на рукаве подарил Сайлас. Она короткая и не попадает в механизм. Красота прекрасно уживается с техникой безопасности.","Silas gave me the pink ribbon on my sleeve. It's short enough to stay out of machinery. Beauty gets along with safety just fine."),
("Отец хотел, чтобы я стал серьёзным мужчиной. Я стал электриком. Трудно придумать что-то серьёзнее провода под напряжением.","My father wanted me to become a serious man. I became an electrician. Few things are more serious than a live wire.")],[
("Неоновые осколки бывают стабильными. Я сравниваю их свечение с лампами — сами образцы можешь оставить себе.","Some neon shards are stable. I compare their glow with the lamps; you can keep the samples."),
("Сначала я отключаю линию, потом чиню. Героический прыжок в искры плохо смотрится в отчёте о несчастном случае.","First I disconnect the circuit, then I repair it. A heroic leap into sparks looks bad in an accident report."),
("Если весь квартал мигает одновременно, дело не в одной лампе. Ищи общую причину, а не самую заметную поломку.","If the entire quarter flickers together, one lamp isn't the problem. Look for a shared cause, not the most visible fault.")],[
("Рен держит для меня кружку без ручки. Я сам её разбил и теперь вспоминаю об этом перед каждым ремонтом: торопиться не надо.","Ren keeps a handleless mug for me. I broke it myself. Before each repair it reminds me not to rush."),
("Мика знает, где во время дождя скапливается вода. Маршрут курьера иногда полезнее старого инженерного плана.","Mika knows where rainwater pools. A courier's route can be more useful than an old engineering plan."),
("Хочу однажды пройти по улице и не заметить ни одной лампы. Когда всё работает, хорошая работа почти невидима.","One day I want to walk down this street without noticing a single lamp. When everything works, good work is nearly invisible.")]),
("emil","Эмиль","Emil",[-7,43],[
("Я Эмиль. Хлеб ещё горячий, а новости уже остыли. Сначала поешь, потом решим, насколько всё ужасно.","I'm Emil. The bread is still hot; the news has gone cold. Eat first, then we'll decide how terrible everything is."),
("Мне говорили, что кружево не подходит широким плечам. Я заказал фартук по размеру. Проблема оказалась в выкройке, а не во мне.","People said lace didn't suit broad shoulders. I ordered an apron that fit. The problem was the pattern, not me."),
("После первой ночи обстрела я испёк слишком много. Соседи пришли с пустыми кастрюлями, и внезапно ничего лишнего не осталось.","After the first night of shelling I baked too much. Neighbors arrived with empty pots, and suddenly nothing was left over.")],[
("Тесто нельзя заставить подняться угрозами. Иногда полезно работать с чем-то, чему совершенно безразлично твоё звание.","You can't threaten dough into rising. It's useful to work with something that couldn't care less about your rank."),
("Рен просит булочки без глазури. Люсьен просит с двойной. Я помечаю корзины цветными лентами, чтобы не перепутать.","Ren wants plain buns. Lucien wants double icing. I mark their baskets with colored ribbons so I don't mix them up."),
("В конце дня хлеб не выбрасываю. Часть забирает медик, часть идёт в сухари. У вчерашней буханки ещё есть работа.","I don't throw bread away at closing. The medic takes some; the rest becomes rusks. Yesterday's loaf still has a job.")],[
("У Мики тяжёлая сумка. Я не подкладываю еду тайком: спрашиваю, есть ли место. Помощь тоже должна быть удобной.","Mika's bag is heavy. I don't secretly add food; I ask if there's room. Help should be convenient too."),
("Иво приносит цветы на прилавок. Покупатели задерживаются, и очередь ворчит. Наверное, это хороший признак.","Ivo brings flowers for the counter. Customers linger and the queue grumbles. I think that's a good sign."),
("Когда дорога станет тише, устроим общий стол. Не пир в честь победителя, а ужин для тех, кто дожил до вечера.","When the road is quieter, we'll share a table. Not a victor's banquet, just supper for everyone who made it through the day.")]),
("yves","Ив","Yves",[7,45],[
("Ив. Садовник без сада — пока. Начинаю с ящиков: корням не нужен торжественный проект, им нужна земля.","Yves. A gardener without a garden, for now. I'm starting with boxes. Roots need soil, not a grand proposal."),
("Юбка удобнее, чем кажется. Для работы я подвязываю подол, а после просто стряхиваю землю. Сайлас добавил глубокие карманы.","A skirt is more practical than it looks. I tie the hem up for work and shake the soil off afterward. Silas added deep pockets."),
("Первый росток здесь погиб. Я записал, что сделал неправильно, и посадил следующий. Надежда иногда похожа на скучный журнал полива.","My first seedling died here. I wrote down what I did wrong and planted another. Sometimes hope looks like a dull watering log.")],[
("Светящиеся семена — красивая сказка. Настоящие гораздо меньше и выглядят как пыль. Главное в них не видно с первого взгляда.","Glowing seeds make a lovely story. Real ones are smaller and look like dust. What matters isn't obvious at first glance."),
("Не поливай растения остатками сладкого чая. Рен уже предупредил постоянных гостей, но я повторю и тебе.","Don't water plants with leftover sweet tea. Ren already warned his regulars, but I'll tell you too."),
("Землю из катакомб я не беру без проверки. Странное свечение не делает её плодородной. Пусть сначала посмотрит учёный.","I don't use catacomb soil without testing it. An eerie glow doesn't make it fertile. Let the scientist inspect it first.")],[
("Иво считает, что цветок должен однажды попасть в чьи-то руки. Я считаю, что иногда достаточно пройти мимо живого куста.","Ivo thinks a flower should eventually reach someone's hands. I think walking past a living bush can be enough."),
("Эш предложил подсветку для рассады. Я попросил сначала починить дорогу. У растений нет срочных вечерних дел, у людей есть.","Ash offered grow lights. I asked him to fix the road first. Plants have no urgent evening errands; people do."),
("Если появится сад, я оставлю место без таблички. Не каждый уголок должен кому-то что-то объяснять.","If we get a garden, I'll leave one corner without a sign. Not every place needs to explain itself.")])
]
dialogues=json.loads((P/"dialogues.json").read_text(encoding="utf-8-sig"))
npcs=json.loads((P/"npcs.json").read_text(encoding="utf-8-sig"))
quests=json.loads((P/"quests.json").read_text(encoding="utf-8-sig"))
ids={p[0] for p in people}
dialogues=[d for d in dialogues if not d["id"].startswith("neighbors_") and d["id"] not in {"giver:"+id for id in ids}]
npcs=[n for n in npcs if n["id"] not in ids]
quests=[q for q in quests if not q["id"].startswith("neighbors_")]
def choice(ru,en,next=None,effects=None):
 d={"text":loc(ru,en)}
 if next: d["next"]=next
 if effects: d["effects"]=effects
 return d
for index,(id,ru,en,pos,bio,craft,city) in enumerate(people):
 # Existing animated world sprite is a temporary stand-in; new art is used for portraits.
 npcs.append(dict(id=id,name_ru=ru,name_en=en,sprite="npc_victor",pos=pos,color=[1,1,1],scene="neighbors_"+id))
 for suffix,lines in [("",bio),("_craft",craft),("_city",city)]:
  options=([choice("Чем могу помочь?","How can I help?","giver:"+id),choice("Расскажи о своём деле.","Tell me about your craft.","neighbors_"+id+"_craft"),choice("Как живёт квартал?","How is the quarter doing?","neighbors_"+id+"_city"),choice("До встречи.","See you.")] if not suffix else [choice("Вернёмся к разговору.","Back to our conversation.","neighbors_"+id)])
  dialogues.append(dict(id="neighbors_"+id+suffix,lines=[dict(speaker=loc(ru,en),portrait=id,text=loc(*line)) for line in lines],choices=options))
# Each author-defined task has its own objective, motivation and response.
tasks=[
("ivo",1,"Цветы к чаю","Flowers for Tea","interact","ren",1,"Узнай у Рена, нужны ли цветы для чайной. Он стоит на восточной стороне площади. Вернись к Иво.","Ask Ren on the east side of the square whether he wants flowers, then return to Ivo.","Не хочу принести огромный букет туда, где он помешает гостям. Сначала спросим хозяина.","I don't want a huge bouquet to inconvenience his guests. Let's ask the host first.","Небольшой букет, без сильного запаха. Хорошо, что спросили: я уже тянулся за лилиями.","A small, unscented bouquet. Good thing we asked; I was already reaching for lilies."),
("ivo",2,"Свет для лепестков","Light for Petals","collect","neon_shard",3,"Собери три неоновых осколка после принятия задания. Иво изучит цвет свечения; предметы останутся у тебя.","Collect three neon shards after accepting. Ivo will study their glow; you keep them.","Хочу подобрать подсветку, которая не превратит розы в пластиковые игрушки. Нужны образцы настоящего свечения.","I want lighting that won't make roses look like plastic toys. I need real glow samples.","Холодный край, тёплая середина. Теперь знаю, о чём попросить Эша. Цветы обойдутся без ослепительной вывески.","Cool edges, warm centers. Now I know what to ask Ash for. The flowers won't need a blinding sign."),
("noel",1,"Свидетель вместо слуха","Witness over Rumor","interact","scientist",1,"Поговори с учёным о голосах катакомб, затем вернись к Ноэлю на южной дороге.","Speak with the scientist about catacomb voices, then return to Noel on the southern road.","В архив принесли три несовместимые версии одного события. Прежде чем переписывать, я хочу услышать специалиста.","Three incompatible accounts reached the archive. Before copying them, I want an expert's opinion.","Оставлю все версии и отмечу источник каждой. Неизвестность — честная запись, если не выдавать её за факт.","I'll keep each account and record its source. Uncertainty is honest when you don't disguise it as fact."),
("noel",2,"Достоверная глубина","A Verified Depth","clear_dungeon","",2,"Пройди второй ярус катакомб и вернись к Ноэлю. Ранее пройденный ярус засчитывается.","Clear catacomb depth two and return to Noel. Earlier completion counts.","На плане второй ярус заканчивается тупиком. В отчётах — боем. Нужен человек, который действительно прошёл туда.","The map ends depth two at a dead end. Reports describe a battle. I need someone who actually went there.","Запишу твой рассказ отдельно от старой схемы. Карта должна предупреждать живых, а не защищать репутацию автора.","I'll record your account beside the old plan. Maps should warn the living, not protect their authors' reputations."),
("lucien",1,"Слушатель у края","A Listener at the Edge","interact","noel",1,"Познакомься с Ноэлем у южной дороги и вернись к Люсьену. Не нужно читать чужие письма.","Meet Noel by the southern road, then return to Lucien. No private letters need reading.","Спроси, удобно ли архиву, когда я репетирую рядом. Сам я каждый раз начинаю говорить о погоде.","Ask whether my rehearsals disturb the archive. Whenever I try, I end up talking about the weather.","Он приходит ради музыки? Тогда завтра сыграю тише в начале, чтобы было слышно, как она появляется.","He comes for the music? Tomorrow I'll start softly, so he can hear it arrive."),
("lucien",2,"Пауза перед концертом","A Pause before the Concert","clear_dungeon","",1,"Пройди первый ярус катакомб и сообщи Люсьену. Предыдущая победа тоже подходит.","Clear the first catacomb depth and tell Lucien. A previous victory counts.","Не хочу назначать праздник, пока люди боятся ближайших врат. Расскажи, когда первый страж будет побеждён.","I won't announce a celebration while people fear the nearest gate. Tell me when the first guardian falls.","Хорошо. Начну с короткого выступления. Людям нужно время привыкнуть, что громкий звук бывает хорошей новостью.","Good. I'll start with a short performance. People need time to remember a loud sound can bring good news."),
("ash",1,"Маршрут сухих ног","A Dry Route","interact","mika",1,"Поговори с Микой у южного входа на площадь о его маршруте, затем вернись к Эшу.","Ask Mika at the southern entrance about his route, then return to Ash.","На старом плане луж нет. У курьера они наверняка есть. Попроси показать опасные места.","Old plans don't show puddles. A courier's mental map will. Ask him about the dangerous spots.","Значит, сначала южный поворот. Приятно получить совет от того, кто каждый день ходит по нашей работе.","The southern turn first, then. It's good to hear from someone who walks across our work every day."),
("ash",2,"Образцы для фонарей","Lamp Samples","collect","neon_shard",3,"Найди три новых неоновых осколка после принятия. После осмотра Эшем они останутся в инвентаре.","Find three new neon shards after accepting. Ash examines them; they remain in your inventory.","Мне нужна стабильная яркость, а не самый сильный всплеск. Принеси три образца для сравнения.","I need steady brightness, not the strongest flash. Bring three samples for comparison.","Эти годятся как эталон. Оставь осколки себе — мне нужны были наблюдения, а не ещё одна опасная коробка.","These work as references. Keep them; I needed observations, not another dangerous box."),
("emil",1,"Заказ без глазури","An Order without Icing","interact","ren",1,"Уточни заказ в чайной Рена на площади и вернись к Эмилю.","Confirm Ren's order at the tea house and return to Emil.","Я помню, что он не любит сладкое, но не помню, сколько гостей ждёт. Лучше спросить, чем испечь наугад.","I remember he dislikes sweets, but not how many guests he expects. Better ask than bake blindly.","Сделаю небольшую партию и оставлю муку на утро. Забота — это ещё и не обещать больше, чем успеешь.","I'll make a small batch and keep flour for morning. Caring also means not promising more than you can manage."),
("emil",2,"Безопасный общий стол","A Safer Shared Table","kill","blood_hound",3,"После принятия победи трёх кровавых гончих на западной окраине или в катакомбах. Вернись к Эмилю.","After accepting, defeat three blood hounds on the western outskirts or in the catacombs. Return to Emil.","Я умею накрывать на стол, но не отбиваться от стаи. Помоги уменьшить угрозу на дороге с припасами.","I can set a table, not fight a pack. Help reduce the danger along the supply road.","Сегодня можно донести корзины без бега. Я всё равно оставлю часового: три побеждённых зверя ещё не означают вечный мир.","We can carry baskets without running today. I'll still post a lookout; three defeated beasts don't mean lasting peace."),
("yves",1,"Сосед по клумбе","A Neighbor in Bloom","interact","ivo",1,"Обсуди с Иво цветы для общего двора и вернись к Иву у южной дороги.","Talk to Ivo about flowers for the shared courtyard and return to Yves by the southern road.","Хочу живую клумбу, а не спор о том, чьи растения красивее. Начнём с разговора, пока не взялись за лопаты.","I want a living flowerbed, not a beauty contest. Let's talk before picking up shovels.","Оставим место и розам, и простой траве. Если двор общий, он не обязан целиком походить на мой вкус.","We'll leave room for roses and ordinary grass. A shared courtyard needn't reflect only my taste."),
("yves",2,"Земля под ногами","Ground beneath Our Feet","clear_dungeon","",3,"Пройди третий ярус катакомб и вернись к Иву. Уже пройденная глубина учитывается.","Clear catacomb depth three and return to Yves. Earlier completion counts.","После толчков из глубины я проверяю каждый ящик. Хочу знать, что там происходит, прежде чем обещать большой сад.","After tremors from below, I check every planter. I need to know what's happening before promising a large garden.","Спасибо. Начну с нескольких крепких ящиков. Сад не вырастет за один разговор, но теперь у меня есть план на завтра.","Thank you. I'll begin with a few sturdy planters. A garden won't grow in one conversation, but now I have a plan for tomorrow.")
]
for id,stage,tr,te,kind,target,count,dr,de,offer_ru,offer_en,end_ru,end_en in tasks:
 person=next(p for p in people if p[0]==id); ru,en=person[1:3]
 qid=f"neighbors_{id}_{stage}"; xp=90 if stage==1 else 240; gold=45 if stage==1 else 110
 q=dict(id=qid,title_ru=tr,title_en=te,desc_ru=dr,desc_en=de,giver=id,chain_ru="Соседи: "+ru,chain_en="Neighbors: "+en,stage=stage,kind=kind,target=target,count=count,reward_xp=xp,reward_gold=gold,reward_items=[dict(id="bread" if stage==1 else "medkit",qty=1)],requires=[] if stage==1 else [f"neighbors_{id}_1"])
 for state in ["offer","progress","complete"]: q[state+"_scene"]=qid+"_"+state
 quests.append(q)
 for state,paragraphs,choices in [
 ("offer",[(offer_ru,offer_en),(dr,de)],[
 choice("Я помогу.","I'll help.",effects=[dict(kind="quest",id=qid,title=loc(tr,te),desc=loc(dr,de))]),choice("Пока не готов.","Not yet.")]),
 ("progress",[(dr,de),("Не торопись ради отчёта. Мне важнее, чтобы ты вернулся целым.","Don't rush just for a report. I'd rather you return in one piece.")],[choice("Вернусь позже.","I'll be back.")]),
 ("complete",[(end_ru,end_en),("Спасибо, что довёл дело до конца. Вот обещанная плата.","Thank you for seeing it through. Here is your payment.")],[choice("Забрать награду.","Collect reward.",effects=[dict(kind="quest_done",id=qid),dict(kind="xp",value=xp),dict(kind="gold",value=gold)])])]:
  dialogues.append(dict(id=qid+"_"+state,lines=[dict(speaker=loc(ru,en),portrait=id,text=loc(*line)) for line in paragraphs],choices=choices))
 # Placeholder allows data graph tooling to see the runtime-dispatched giver ID.
for id,ru,en,*_ in people:
 dialogues.append(dict(id="giver:"+id,lines=[dict(speaker=loc(ru,en),portrait=id,text=loc("Поговорим о делах квартала.","Let's discuss neighborhood work."))]))
modern = {
 "ivo": [("Я парень, которому нравятся сетка, подводка и розы. Это не сценический номер: я так хожу за продуктами и чиню холодильник для цветов.", "I'm a guy who likes mesh, eyeliner and roses. It isn't a stage act; I dress this way to buy groceries and repair the flower fridge."), ("На фартуке датчик влажности, в ухе дешёвый коммуникатор. Красивый букет теперь начинается ещё и с заряженного аккумулятора.", "My apron has a humidity sensor and my ear a cheap communicator. A beautiful bouquet now also starts with a charged battery."), ("Не хочу, чтобы наш квартал выглядел музейной витриной. Пусть рядом с кружевом будут граффити, провода и вещи, которые мы сделали сами.", "I don't want our quarter to look like a museum display. Lace can share space with graffiti, cables and things we made ourselves.")],
 "noel": [("Мне нравится женственный образ, но называй меня он. Если забудешь — поправлю, и продолжим разговор. Экзамен на идеального собеседника я не принимаю.", "I like a feminine look, but use he for me. If you forget, I'll correct you and we'll move on. This isn't an exam in perfect conversation."), ("Архив хранится на локальных накопителях. Когда внешняя сеть падает, память города не должна падать вместе с ней.", "The archive lives on local drives. When the outside network fails, the city's memory shouldn't fail with it."), ("AR-очки показывают номера полок, а не мысли людей. Вторую функцию кто-то постоянно пытается мне приписать.", "My AR glasses show shelf numbers, not people's thoughts. Everyone seems determined to credit them with the second feature.")],
 "lucien": [("Мне близок sissy-стиль: банты, глянец, короткая юбка, очень много розового. Для меня это собственный выбор образа, а не приглашение обращаться со мной свысока.", "I like sissy style: bows, gloss, a short skirt and a lot of pink. For me it's a chosen look, not an invitation to talk down to me."), ("Я парень. Эш — женщина. Мы можем носить похожие чокеры, но одинаковые вещи не делают наши истории одинаковыми.", "I'm a guy. Ash is a woman. We might wear similar chokers, but matching accessories don't make our stories identical."), ("Скрипка электрическая, ритм идёт с маленького драм-пада. Люблю, когда нежная мелодия встречается с грязным басом.", "My violin is electric and the rhythm comes from a little drum pad. I love a gentle melody meeting a dirty bass line.")],
 "ash": [("Я транс-женщина. Здесь меня знают как Эш, мастерицу по свету. О переходе расскажу, если сама захочу; с неисправной проводкой можешь обращаться сразу.", "I'm a trans woman. Around here I'm Ash, the lighting technician. I'll discuss my transition when I choose to; faulty wiring can come straight to me."), ("На протезе открытая прошивка. Не хочу, чтобы чья-то подписка решала, когда мне пользоваться собственной рукой.", "My prosthetic runs open firmware. I won't let someone's subscription decide when I can use my own hand."), ("Панк для меня — уметь чинить, делиться схемами и не спрашивать у корпорации, разрешено ли нам жить красиво.", "Punk means repairing things, sharing schematics and not asking a corporation for permission to live beautifully.")],
 "emil": [("Да, у меня пирсинг и розовый фартук. Нет, от этого тесто не поднимается быстрее. Я проверял: ему важнее температура.", "Yes, I have piercings and a pink apron. No, that doesn't make dough rise faster. I checked; it cares more about temperature."), ("На печи цифровой контроллер, но рецепты записаны и на бумаге. Когда экран гаснет, завтрак всё равно должен состояться.", "The oven has a digital controller, but the recipes also exist on paper. Breakfast should happen even when the screen goes dark."), ("Моя футболка от местной группы. Они расплатились концертом, я — булочками. Кажется, обе стороны считают, что выиграли.", "My shirt is from a local band. They paid with a concert and I paid with buns. Both sides think they got the better deal.")],
 "yves": [("Мне нравятся юбки с утилитарными карманами и тяжёлые ботинки. В одном кармане блеск для губ, в другом — датчик кислотности почвы.", "I like skirts with utility pockets and heavy boots. One pocket holds lip gloss; another holds a soil pH sensor."), ("Система полива работает без облачного сервиса. Если компания исчезнет, растения не должны узнавать об этом первыми.", "The watering system works without a cloud service. If a company disappears, the plants shouldn't be the first to find out."), ("Мы не обязаны выбирать между живым садом и технологиями. Вопрос в том, кому эти технологии помогают и кто умеет их починить.", "We don't have to choose between living gardens and technology. The question is who benefits and who can repair it.")]
}
for id, ru, en, *_ in people:
 intro=next(d for d in dialogues if d['id']=='neighbors_'+id)
 intro['choices'].insert(3, choice("Твой стиль и технологии?", "Your style and technology?", "neighbors_"+id+"_style"))
 dialogues.append(dict(id="neighbors_"+id+"_style",lines=[dict(speaker=loc(ru,en),portrait=id,text=loc(*line)) for line in modern[id]],choices=[choice("Вернёмся к разговору.","Back to our conversation.","neighbors_"+id)]))
ash=next(d for d in dialogues if d['id']=='neighbors_ash')
ash['lines'][2]['text']=loc("Отец хотел, чтобы я стала серьёзным человеком. Я стала электриком. И женщиной, которой давно себя знала. С первым он согласился быстрее.", "My father wanted me to become a serious person. I became an electrician, and the woman I already knew myself to be. He accepted the first part sooner.")
for stem,data in [("npcs",npcs),("quests",quests),("dialogues",dialogues)]:
 (P/(stem+".json")).write_text(json.dumps(data,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
print("Added: 6 NPC, 12 quests, 66 dialogue scenes, 150 lines in RU and EN.")
